name: Target Workflow

on:
  repository_dispatch:
    types: [test-run] # Replace with a descriptive event type

jobs:
  target_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Update parent version in pom.xml
        run: |
          updated_version="${{ github.event.client_payload.updated-version }}"
          echo "Updating parent version to $updated_version"
          sed -i '/<parent>/,/<\/parent>/ s|<version>.*</version>|<version>$updated_version</version>|' pom.xml

      # - name: Commit pom parent version update
      #   env:
      #     GH_PAT: ${{ secrets.fdsfsdffwfw }}
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add pom.xml
      #     git commit -m "Update parent version to ${{ github.event.client_payload.updated-version }}"
      #     git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'pom.xml'

        # The name of the user that will be displayed as the author of the commit.
        # Default: depends on the default_author input
        author_name: Github Actions

        # The email of the user that will be displayed as the author of the commit.
        # Default: depends on the default_author input
        author_email: mail@example.com

        # Additional arguments for the git commit command. The --message argument is already set by the message input.
        # Default: ''
        #commit: 'Update parent version to ${{ github.event.client_payload.updated-version }}'

        # The name of the custom committer you want to use, if different from the author of the commit.
        # Default: the name of the author (set with either author_name or default_author)
        committer_name: Github Actions

        # The email of the custom committer you want to use, if different from the author of the commit.
        # Default: the email of the author (set with either author_email or default_author)
        committer_email: mail@example.com

        # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
        # Default: '.'
        #cwd: './path/to/the/repo'

        # Determines the way the action fills missing author name and email. Three options are available:
        # - github_actor -> UserName <UserName@users.noreply.github.com>
        # - user_info -> Your Display Name <your-actual@email.com>
        # - github_actions -> github-actions <email associated with the github logo>
        # Default: github_actor
        default_author: github_actor

        # Arguments for the git fetch command. If set to false, the action won't fetch the repo.
        # For more info as to why fetching is usually recommended, please see the "Performance on large repos" FAQ. 
        # Default: --tags --force
        fetch: true

        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Update parent version to ${{ github.event.client_payload.updated-version }}'

        # If this input is set, the action will push the commit to a new branch with this name.
        # Default: ''
        #new_branch: custom-new-branch

        # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
        # - ignore -> errors will be logged but the step won't fail
        # - exitImmediately -> the action will stop right away, and the step will fail
        # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
        # Default: ignore
        pathspec_error_handling: ignore

        # Arguments for the git pull command. By default, the action does not pull.
        # Default: ''
        #pull: '--rebase --autostash ...'

        # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
        # Default: true
        #push: false

        # The arguments for the `git rm` command (see the paragraph below for more info)
        # Default: ''
        #remove: './dir/old_file.js'

        # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
        # Default: ''
        #tag: 'v1.0.0 --force'

        # Arguments for the git push --tags command (any additional argument will be added after --tags)
        # Default: ''
        #tag_push: '--force'
